version: 2

references:
  container_config: &container_config
    docker:
      - image: node:6.7.0
    working_directory: ~/circleci-demo-workflows

  workspace_root: &workspace_root
      /tmp

  attach_workspace: &attach_workspace
    attach_workspace:
      at: *workspace_root

  load_code: &load_code
    run:
      name: load code from workspace
      command: |
          # Move all files and dotfiles to current directory
          mv /tmp/workspace/* /tmp/workspace/.[!.]* .

jobs:
  job1:
    <<: *container_config
    steps:
      - checkout
      - run:
          command: |
              mkdir -p /tmp/workspace
              mv * .[!.]* /tmp/workspace/
      - persist_to_workspace:
          root: *workspace_root
          paths:
            - workspace
  job2:
    <<: *container_config
    steps:
      - *attach_workspace
      - *load_code
      - run:
          name: set env
          command: echo "[deploy]" >> ~/.aws/credentials
          command: echo $CIRCLE_BRANCH >> ~/.aws/credentials
  job3:
    <<: *container_config
    steps:
      - *attach_workspace
      # - *load_code
      - run:
          name: show
          command: cat ~/.aws/credentials
      - run:
          name: pwd
          command: pwd
      - run:
          name: ls
          command: ls -la
workflows:
  version: 2
  build_flow:
    jobs:
      - job1
      - job2
          requires:
            - job1
      - job3
          requires:
            - job2
