version: 2


references:
  container_config: &container_config
    docker:
      - image: node:6.7.0
    working_directory: ~/circleci-demo-workflows

jobs:
  job1:
    <<: *container_config
    branches:
      only:
        - master
        - stg
        - dev
        - /feature.*/
    steps:
      - checkout
      - run:
          name: pwd
          command: pwd
  job2:
    docker:
      - image: node:6.7.0
    working_directory: ~/circleci-demo-workflows
    branches:
      only:
        - master
        - stg
        - dev
        - /feature.*/
    steps:
      - run:
          name: set env
          command: echo "[deploy]" >> ~/.aws/credentials
          command: echo $CIRCLE_BRANCH >> ~/.aws/credentials
  job3:
    <<: *container_config
    branches:
      only:
        - master
        - stg
        - dev
        - /feature.*/
    steps:
      - run:
          name: show
          command: cat ~/.aws/credentials
workflows:
  version: 2
  deploy_flow:
    jobs:
      - job1
      - job2
      - job3
