version: 2
jobs:
  unittest:
    docker:
      - image: docker:17.05.0-ce-git
    working_directory: /var/workspace
    steps:
      - checkout
      - setup_remote_docker
      - run:
          name: echo a
          command: echo "AAAAAAAAAAAA"
  deploy:
    docker:
      - image: node:6.7.0
    working_directory: /var/workspace
    steps:
      - checkout
      - run:
          name: echo b
          command: echo "BBBBBBBBB"
workflows:
  version: 2
  build_accept_deploy:
    jobs:
      - unittest
      - deploy:
          requires:
            - unittest
