version: 2

jobs:
  deploy_serverless:
    docker:
      - image: circleci/node:4.8.2
    working_directory: ~/circleci-demo-workflows
    steps:
      - checkout
      - run:
          name: sercerless deploy shell
          command: sh ./ci/deploy_dev.sh

workflows:
  version: 2
  deploy_flow:
    jobs:
      - deploy_serverless
