version: 2

jobs:
  deploy_serverless:
    docker:
      - image: node:6.7.0
    working_directory: ~/circleci-demo-workflows
    branches:
      only:
        - master
        - stg
        - dev
        - /feature.*/
    steps:
      # - checkout
      # - run:
      #     name: install serverless framework
      #     command: npm install -g serverless
      - run:
          name: pwd
          command: pwd
      - run:
          name: list
          command: ls -la
      - run:
          name: show environment variables
          command: printenv
      # - run:
      #     name: serverless deploy
      #     command: sh ./ci/deploy_dev.sh
      # - run:
      #     name: serverless deploy
      #     command: serverless deploy --region us-east-2

workflows:
  version: 2
  deploy_flow:
    jobs:
      - deploy_serverless
