service: aws-deploy-ci

provider:
  name: aws
  runtime: python3.6
  stage: vtest
  region: ${opt:region, self:custom.defaultRegion}
  iamRoleStatements:
    - Effect: "Allow"
      Action:
        - "dynamodb:*"
      Resource:
        - "arn:aws:dynamodb:${opt:region, self:custom.defaultRegion}:*:table/*"
    - Effect: "Allow"
      Action:
        - "states:*"
      Resource:
        - "*"

custom:
  defaultRegion: us-east-2

# package:
#   include:
#     - lib
#     - app
#     - repository
#     - utils

functions:
  accounts-account-id-campaigns-post:
    handler: fuga.get
    timeout: 60
    events:
      - http:
          path: hoge/fuga
          method: post
          cors: true
          integration: lambda
          request:
            parameters:
              headers:
                Authorization: true
              querystrings:
                user_id: false
                name: false
            template:
              application/json: ${file(./definitions/common.yml):requestTemplates}
          response:
            statusCodes:
              ${file(./definitions/common.yml):responseTemplates}
            headers:
              ${file(./definitions/common.yml):postCorsHeaders}
